#############################################################################
# Makefile for building: UPX_GUI_Static
# Generated by qmake (3.1) (Qt 6.5.3)
# Project:  upx_gui_static.pro
# Template: app
# Command: D:/Computer/Qt653/6.5.3/mingw_64/bin/qmake.exe -o Makefile upx_gui_static.pro -spec win32-g++ CONFIG+=release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = D:/Computer/Qt653/6.5.3/mingw_64/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = D:/Computer/Qt653/6.5.3/mingw_64/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = D:/Computer/Qt653/6.5.3/mingw_64/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = midl
ZIP           = 
DEF_FILE      = 
RES_FILE      = UPX_GUI_Static_resource_res.o
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: upx_gui_static.pro D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/win32-g++/qmake.conf D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/spec_pre.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/device_config.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/sanitize.conf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/gcc-base.conf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/g++-base.conf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/windows-vulkan.conf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/g++-win32.conf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/windows-desktop.conf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/qconfig.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_ext_freetype.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_ext_libjpeg.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_ext_libpng.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_bluetooth.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_charts.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_charts_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_chartsqml.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_concurrent.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_core.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_core5compat.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_core_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_dbus.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_designer.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_designer_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_freetype_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_gui.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_gui_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_help.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_help_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssettings.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_linguist.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimedia.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_network.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_network_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_nfc.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_nfc_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_opengl.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_png_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_positioning.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_positioning_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_positioningquick.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_printsupport.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qml.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qml_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltest.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_scxml.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_scxml_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialport.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialport_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_shadertools.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_spatialaudio.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_sql.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_sql_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_statemachine.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_svg.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_svg_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_testlib.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_tools_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_uitools.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_webchannel.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_websockets.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_websockets_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_widgets.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_xml.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_xml_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/qt_functions.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/qt_config.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/win32-g++/qmake.conf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/exclusive_builds.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/toolchain.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/default_pre.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/win32/default_pre.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/resolve_config.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/exclusive_builds_post.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/default_post.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/entrypoint.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/precompile_header.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/warn_on.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/qt.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/resources_functions.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/resources.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/moc.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/win32/opengl.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/uic.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/qmake_use.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/file_copies.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/win32/windows.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/testcase_targets.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/exceptions.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/yacc.prf \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/lex.prf \
		upx_gui_static.pro \
		D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6Widgets.prl \
		D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6Gui.prl \
		D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6Network.prl \
		D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6Core.prl \
		D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6EntryPoint.prl \
		D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/build_pass.prf \
		resources.qrc
	$(QMAKE) -o Makefile upx_gui_static.pro -spec win32-g++ CONFIG+=release
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/spec_pre.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/device_config.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/sanitize.conf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/gcc-base.conf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/g++-base.conf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/windows-vulkan.conf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/g++-win32.conf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/common/windows-desktop.conf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/qconfig.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_ext_freetype.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_ext_libjpeg.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_ext_libpng.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_bluetooth.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_charts.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_charts_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_chartsqml.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_concurrent.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_core.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_core5compat.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_core5compat_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_core_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_dbus.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_designer.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_designer_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_example_icons_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_freetype_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_gui.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_gui_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_help.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_help_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_jpeg_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssettings.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_linguist.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimedia.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimedia_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimediaquick_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_network.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_network_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_nfc.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_nfc_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_opengl.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_png_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_positioning.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_positioning_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_positioningquick.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_printsupport.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qml.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qml_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlintegration.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltest.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quick_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_scxml.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_scxml_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_scxmlqml.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_scxmlqml_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialport.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_serialport_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_shadertools.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_shadertools_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_spatialaudio.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_spatialaudio_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_sql.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_sql_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_statemachine.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_statemachine_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_statemachineqml.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_statemachineqml_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_svg.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_svg_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_testlib.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_tools_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_uitools.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_webchannel.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_webchannel_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_websockets.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_websockets_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_widgets.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_xml.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_xml_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/qt_functions.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/qt_config.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/win32-g++/qmake.conf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/spec_post.prf:
.qmake.stash:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/exclusive_builds.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/toolchain.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/default_pre.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/win32/default_pre.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/resolve_config.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/exclusive_builds_post.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/default_post.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/entrypoint.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/precompile_header.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/warn_on.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/qt.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/resources_functions.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/resources.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/moc.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/win32/opengl.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/uic.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/qmake_use.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/file_copies.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/win32/windows.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/testcase_targets.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/exceptions.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/yacc.prf:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/lex.prf:
upx_gui_static.pro:
D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6Widgets.prl:
D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6Gui.prl:
D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6Network.prl:
D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6Core.prl:
D:/Computer/Qt653/6.5.3/mingw_64/lib/Qt6EntryPoint.prl:
D:/Computer/Qt653/6.5.3/mingw_64/mkspecs/features/build_pass.prf:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile upx_gui_static.pro -spec win32-g++ CONFIG+=release

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
